### ISSUE TITLE
Unable to run MyCompany using visual studio

### ISSUE THREAD

**Issue by vikram-v** [xamarin/MyCompany#1]
I am unable to run the MyCompany ios project from visual studio. Below is the build error i am facing,
<code>
3>Task "Message"
3>Task Parameter:Text=Uploading changes...
3>Uploading changes...
3>Done executing task "Message".
3>Using "MonoTouchBuildNative_UploadChanges" task from assembly "C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.MonoTouch.Build.Tasks.dll".
3>Task "MonoTouchBuildNative_UploadChanges"
3>Task Parameter:ProjectGuid={E473AB4E-2896-4637-B81E-4078483E3885}
3>Task Parameter:ProjectDirectory=C:\Users\vikra_000\Downloads\MyCompany-master\MyCompany-master\MyCompany.Visitors.Client.iOS\
3>Synchronizing with the remote server
3>Done executing task "MonoTouchBuildNative_UploadChanges".
3>Task "Message"
3>Task Parameter:Text=Building...
3>Building...
3>Done executing task "Message".
3>Using "MonoTouchBuildNative_Build" task from assembly "C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.MonoTouch.Build.Tasks.dll".
3>Task "MonoTouchBuildNative_Build"
3>Task Parameter:ProjectGuid={E473AB4E-2896-4637-B81E-4078483E3885}
3>Building application on the remote server
3>Server command 'Build': application remote build failed
3>Command execution task ended with exception
3>Exception System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
3>Exception details can be found in the log file
3>
3>
3>Remote build step failed.
3>Done executing task "MonoTouchBuildNative_Build" -- FAILED.
3>Done building target "_BuildNativeApplication" in project "MyCompany.Visitors.Client.iOS.csproj" -- FAILED.
3>Done building project "MyCompany.Visitors.Client.iOS.csproj" -- FAILED.
3>Build FAILED.
========== Build: 1 succeeded, 0 failed, 0 up-to-date, 1 skipped ==========
========== Deploy: 0 succeeded, 1 failed, 0 skipped ==========
<code>

**Comment by ibonilm** [comment]
I have the same issue...Any solution?

**Comment by vikram-v** [comment]
I changed the images which were added ("as link") under resource folder to embedded resource in properties and it started working for me. Not sure if it is the correct fix.

**Comment by jamesmontemagno** [comment]
I have fixed this up. Thank you for filing this.

**Comment by ibonilm** [comment]
It doesn´t work for me. After the latest change the application is deployed...but I get an error calling the FromBundle("backgrounf") method.

After changing some images from image directory to resource directory it works. The build action for the copied files is BundleResource.

**Comment by jamesmontemagno** [comment]
Let me re-open and see what is going on.

**Comment by jamesmontemagno** [comment]
I think I figured out what is going on here. I believe the issue has to do with some of the images being linked. I have reset the images to the Resources directory and marked as BundleResource via docs: http://docs.xamarin.com/guides/ios/user_interface/controls/part_5_-_images/ so they load correct. @ibonilm can you check this after my next checkin?

**Comment by jamesmontemagno** [comment]
Should be pushed now.

**Comment by ibonilm** [comment]
It Works for me now!
